name: ML-PROJECT
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11  # Compatible with all libs
  - numpy=1.26.2
  - pandas=2.1.4
  - geopandas=0.14.1
  - shapely=2.0.2
  - scikit-learn=1.3.2
  - xgboost=2.0.3
  - joblib=1.3.2
  - matplotlib=3.8.2
  - seaborn=0.13.0
  - openpyxl=3.1.2  # For XLSX
  - folium=0.15.1
  - pip  # For Streamlit
  - pip:
    - streamlit==1.29.0
    - streamlit-folium==0.14.0  # Folium integration